// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BullyingDetectionService.proto

package com.edu.greenwich.managementsystem.grpc;

public interface MsgRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.edu.greenwich.managementsystem.grpc.MsgRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
