// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BullyingDetectionService.proto

package com.edu.greenwich.managementsystem.grpc;

public interface MsgResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.edu.greenwich.managementsystem.grpc.MsgResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string response = 1;</code>
   */
  java.lang.String getResponse();
  /**
   * <code>string response = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseBytes();
}
